version: '3.9'
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    volumes: 
      - ./db_data:/var/opt/mssql/data
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "MpA2005mPa"
      ACCEPT_EULA: "Y"